server:
  port: 9099

spring:
  application:
    name: CONFIGSERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-username/your-config-repo.git  # 🔁 Replace with your Git repo URL
          clone-on-start: true
          default-label: main  # or 'master' if your repo uses that

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
